name: Release

on:
  push:
    branches:
      - develop
      - release
      - master

jobs:
  build:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Terraform Validate
      if: github.ref == 'refs/heads/develop'
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_PASS: ${{ secrets.GIT_PASS }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
      run: |
        sudo apt-get update
        sudo apt-get -y install curl
        curl -s https://releases.hashicorp.com/terraform/0.13.6/terraform_0.13.6_linux_amd64.zip -o terraform_0.13.6_linux_amd64.zip
        unzip terraform_0.13.6_linux_amd64.zip && chmod +x terraform && sudo mv terraform /usr/bin/
        terraform init -backend=false
        terraform validate
        NUM=$(curl -s -u ${GIT_USER}:${GIT_PASS} -H "Content-Type:application/json" -X POST https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls -d '{"title": "release", "head": "develop", "base": "release"}' | jq .number)
        curl -s -u ${GIT_USER}:${GIT_PASS} -H "Accept: application/vnd.github.v3+json" -X PUT https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${NUM}/merge -d '{"commit_title":"release", "merge_method": "merge"}'

    - name: Awspec
      if: github.ref == 'refs/heads/release'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_PASS: ${{ secrets.GIT_PASS }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
      run: |
        sudo apt-get update
        sudo apt-get -y install curl awscli
        curl -s https://releases.hashicorp.com/terraform/0.13.6/terraform_0.13.6_linux_amd64.zip -o terraform_0.13.6_linux_amd64.zip
        unzip terraform_0.13.6_linux_amd64.zip && chmod +x terraform && sudo mv terraform /usr/bin/
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec kitchen test
        NUM=$(curl -s -u ${GIT_USER}:${GIT_PASS} -H "Content-Type:application/json" -X POST https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls -d '{"title": "release", "head": "release", "base": "master"}' | jq .number)
        curl -s -u ${GIT_USER}:${GIT_PASS} -H "Accept: application/vnd.github.v3+json" -X PUT https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${NUM}/merge -d '{"commit_title":"release", "merge_method": "merge"}'

    - name: Release
      if: github.ref == 'refs/heads/master'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_PASS: ${{ secrets.GIT_PASS }}
      run: |
        sudo apt-get update
        sudo apt-get -y install curl awscli
        bash tagging.sh